FROM scratch
MAINTAINER Simba Zhang <solderzzc@users.noreply.github.com>
ADD root.tar /
#ADD assets/qemu-arm-static /usr/bin/qemu-arm-static

# Unfortunately we have to use codenames here rather than something more
# static (stable/testing) because we wouldn't want the images to suddenly
# change suite when a new Debian release was made. Thus these greps will
# need to be updated to track the current release codenames
RUN echo "deb http://archive.raspbian.org/raspbian jessie main" > /etc/apt/sources.list

RUN apt-get update \
	&& apt-get -y upgrade \
	&& apt-get -y autoremove \
	&& apt-get clean \
	&& find /var/lib/apt/lists -type f -delete

LABEL org.redmars.docker.VcsType git
LABEL org.redmars.docker.VcsUrl  http://github.com/jmtd/debian-docker
LABEL org.redmars.docker.VcsRef  b34be278c4cc53d3f1809439cd42d78b9c92f755

CMD ["/bin/bash"]
